album/urls.py
from django.conf.urls import url
from album import views 

urlpatterns=[
	url (r'^$',views.first_view, name='first_view'),
	url (r'^category/$',views.category, name='category-list'),
	url (r'^category/(?P<category_id>[0-9]+)/detail/$',views.category_detail, name='category-detail'),
	url (r'^photo/$',views.PhotoListView.as_view(), name='photo-list'),
	url (r'^photo/(?P<pk>[0-9]+)/detail/$',views.PhotoDetailView.as_view(), name='photo-detail'),
	url (r'^photo/(?P<pk>[0-9]+)/update/$',views.PhotoUpdate.as_view(), name='photo-update'),
	url (r'^photo/(?P<pk>[0-9]+)/delete/$',views.PhotoDelete.as_view(), name='photo-delete'),







]

myapps/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
	url(r'^album/', include('album.urls') ),
    url(r'^admin/', admin.site.urls),
    


]

album/models.py
from django.db import models
from django.core.urlresolvers import reverse 


class Category(models.Model):
    """ Categorias para clasificar las fotos """
    name = models.CharField(max_length=50)
    def __str__(self):             
        return self.name

class Photo(models.Model):
	"""Fotos del album"""
	category=models.ForeignKey(Category,null=True,blank=True)
	title=models.CharField(max_length=50,default='No title')
	photo=models.ImageField(upload_to='photos/')
	pub_date=models.DateField(auto_now_add=True)
	favorite=models.BooleanField(default=False)
	comment=models.CharField(max_length=200,blank=True)

	def get_absolute_url(self):
		return reverse('photo-list')

	def __str__(self):
		return self.title


class Estudiante(models.Model):
	"""estudiantes"""
	email=models.EmailField(max_length=50)
	nombres=models.CharField(max_length=100,blank=True)
	apellidos=models.CharField(max_length=100,blank=True)
	direccion=models.CharField(max_length=200,blank=True)
	fecha_nac=models.DateField(auto_now_add=False)
	observaciones=models.TextField()
	def __str__(self):
		return self.nombres+" "+self.apellidos

album/views.py
from django.shortcuts import render
from django.http import HttpResponse
from album.models import Category, Photo
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.core.urlresolvers import reverse_lazy

# Create your views here.
class PhotoUpdate(UpdateView):
	model= Photo
	fields='__all__' 


class PhotoDelete(DeleteView):
	model= Photo
	fields='__all__'
	success_url=reverse_lazy ('photo-list')

def first_view (request):
	return HttpResponse('<H1>Esta es mi primer vista!!!</H1>')

class PhotoListView(ListView):
	model=Photo

class PhotoDetailView(DetailView):
	model=Photo


def category(request):
	category_list=Category.objects.all()
	context = {'object_list':category_list}
	return render(request, 'album/category.html', context)

def category_detail(request, category_id):
	category=Category.objects.get(id= category_id)
	context = {'object':category}
	return render(request, 'album/category_detail.html', context)

album/templates/album/category.html
{% extends 'base.html' %}
{% block section %}
	<h2>Category</h2>
	<hr>
{% endblock section %}
{% block maincontent %}
<div>	
	{% for c in object_list %}
	<a href="{% url 'category-detail' c.pk %}">
		{{c.name}}
	</a>
	{% endfor %}	
</div>
{% endblock maincontent %}

album/templates/album/category_detail.html
{% extends 'base.html' %}
{% load static %}
{% block section %}
	<h2>{{ object.name}}</h2>
	<hr>
{% endblock section %}
{% block maincontent %}
<div>
	<table border= "1px">
		<tr>
			{% for p in object.photo_set.all %}
				<td>
					<div>
						{{p.title}}
					</div>
					<div>
						<a href=">{{% url 'photo-detail' p.id }">
							<img src= "{% static p.photo.url %}" style="width: 200px; height: 200px"/>
						</a>	
					</div>
				</td>
				{% endfor %}
		</tr>
	</table>


		
</div>
{% endblock maincontent %}



{{object.id}}, {{object.name}} {{object.photo_set.all}}

album/templates/album/photo_confirm_delete.html
 extends 'base.html' %}
{% block maincontent %}
<form action="" method="post">{% csrf_token %}
<p>Delete "{{ object.title }}"?</p>
<input type="submit" value="Confirm"/>
<a class='btn' href="{% url 'photo-list' %}">Cancel</a>
</form>
{% endblock maincontent %}

album/templates/album/photo_detail.html
{% extends 'base.html' %}
{% load static %}
{% block section %}
<h2>
	{{ object.title }}
	{% if object.favorite %}
	&#9733;
	{% else %}
	&#9734;
	{% endif %}
	{% if object.category_id %}
	( <a href="{% url 'category-detail' object.category_id %}">{{object.category}}</a> )
	{% endif %}
</h2>
<p><strong>comments: </strong>{{ object.comment|default:"no comments" }}</p>
<a href="{% url 'photo-update' object.id %}">edit</a>
<a href="{% url 'photo-delete' object.id %}">delete</a​>
	<hr>
	{% endblock section %}
	{% block maincontent %}
	<div>
		<div>
			<img src="{% static object.photo.url %}" style="width:550px;height:420px"/>
		</div >
	</div>
	{% endblock maincontent %}

album/templates/album/photo_form.html
{% extends "base.html" %}
{% block maincontent %}
<form enctype= "multipart/form-data" method="post" action="">
 	{% csrf_token %}
 	{{ form.as_p}}
 	<button type="submit"> SAVE </button>
 	<a href="{% url 'photo-list' %}"></a>
 </form>
 {% endblock maincontent %}

album/templates/album/photo_list.html
{% extends 'base.html' %}
{% load static %}
{% block section %}
<h2>Photo</h2>
<hr>
{% endblock section %}
{% block maincontent %}
	{% for p in object_list.all %}
				<h3 >{{ p.title }}</h3>
			  <a href="{% url 'photo-detail' p.id %}">
					<img src="{% static p.photo.url %}" style="width:200px;height:200px;"/>
				</a>
	{% endfor %}
{% endblock maincontent %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Album</title>
</head>
<body>
	<h1>Album</h1>
	<ul>
		<li>
			<a href="{% url 'category-list' %}">
			category
		</li>
		<li>
			<a href="{% url 'photo-list' %}">
			photo
			</a>
		</li>
	</ul>
	<hr>
	<div>
			{% block section %}
			{% endblock section %}
	</div>	
	<div>
			{% block maincontent %}
			{% endblock maincontent %}
	</div>

</body>
</html>